apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
  labels:
    app: angular
spec:
  replicas: 2
  selector:
    matchLabels:
      app: angular
  template:
    metadata:
      labels:
        app: angular
    spec:
      containers:
      - name: angular-app
        image: usuario/angular-app:latest  # Usa la imagen subida a DockerHub
        ports:
        - containerPort: 80
